config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#index'

  namespace :inspection do
    resources :results
    resources :histories do
      member do
        get 'pdf', as: :pdf
      end
    end
  end

  resources :areas do
    collection do
      get 'guide'
    end

    member do
      get 'map_image'
    end
  end
  resources :corporations

  resources :users do
    collection do
      get 'query'
    end
  end

  namespace :user do
    resources :operation_histories
  end

  namespace :equipment do
    resources :groups
    resources :components
    resources :meta_data do
      member do
        get 'download_pdf', as: :download_pdf
      end
    end
    resources :items do
      collection do
        get 'guide'
        get 'management'
        get 'create_inspection'
      end

      member do
        get 'map_image'
      end
      resources :inspection_histories, controller: '/inspection/histories'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'sign_in', to: 'sessions#new', as: :new_session
  post 'sign_in', to: 'sessions#create', as: :create_session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_session

  scope controller: :api, path: '/api', as: :api do
    get 'get_layer2' => :get_layer2, as: :get_layer2
    get 'get_equ_component' => :get_equ_component, as: :get_equ_component
  end

  get 'qrcode_download', to: 'qrcode_download#index', as: :qrcode_download
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  name            :string           not null
#  password_digest :string           not null
#  role            :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  corporation_id  :bigint
#
# Indexes
#
#  index_users_on_corporation_id  (corporation_id)
#  index_users_on_name            (name) UNIQUE
#
class User < ApplicationRecord
  has_secure_password

  SUPER_ADMIN = 'super_admin'
  ADMIN       = 'admin'
  USER        = 'user'
  VIEWER      = 'viewer'
  CORP_USER   = 'corp_user'

  CH_ROLES_MAPPING = {
    SUPER_ADMIN => '超級管理者',
    ADMIN => '管理者',
    USER => '使用者',
    VIEWER => '瀏覽者',
    CORP_USER => '廠商使用者'
  }.freeze

  enum role: {
    super_admin: SUPER_ADMIN,
    admin: ADMIN,
    user: USER,
    viewer: VIEWER,
    corp_user: CORP_USER
  }.freeze

  has_many :operation_histories, class_name: 'User::OperationHistory', dependent: :destroy
  belongs_to :corporation, optional: true

  validates :name,
            presence: { message: '使用者名稱不可為空' },
            uniqueness: { message: '已經存在的使用者名稱' }

  def ch_role
    CH_ROLES_MAPPING[role]
  end
end

app/models/user/operation_history.rb
# == Schema Information
#
# Table name: user_operation_histories
#
#  id          :bigint           not null, primary key
#  action_type :string
#  note        :text
#  operated_at :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_user_operation_histories_on_user_id  (user_id)
#
class User::OperationHistory < ApplicationRecord
  belongs_to :user

  enum action_type: {
    sign_in: '登入',
    create_account: '新增帳號',
    change_password: '修改密碼',
    create: '資料新增',
    update: '資料修改',
    destroy: '資料刪除',
    upload_image: '上傳圖片'
  }, _prefix: :action

  ACTION_TYPE_MAPPING = {
    sign_in: '登入',
    create_account: '新增帳號',
    change_password: '修改密碼',
    create: '資料新增',
    update: '資料修改',
    destroy: '資料刪除',
    upload_image: '上傳圖片'
  }

  def action
    ACTION_TYPE_MAPPING[action_type&.to_sym]
  end
end

app/controllers/user/operation_histories_controller.rb
class User::OperationHistoriesController < ApplicationController
  before_action :set_user_operation_history, only: [:show, :edit, :update, :destroy]

  # GET /user/operation_histories
  # GET /user/operation_histories.json
  def index
    query = User::OperationHistory

    if params[:from] && params[:to]
      year, month, day = params[:from].values_at(:year, :month, :day).map(&:to_i)

      @from = Time.zone.parse("#{year}-#{month}-#{day}")

      year, month, day = params[:to].values_at(:year, :month, :day).map(&:to_i)

      @to = Time.zone.parse("#{year}-#{month}-#{day}")

      query = query.where(created_at: @from..@to)
    end

    if params[:action_type] && params[:action_type] != 'all'
      query = query.where(action_type: params[:action_type])
    end

    @user_operation_histories = query.order(created_at: :desc).page(params[:page]).per(20)
  end

  # GET /user/operation_histories/1
  # GET /user/operation_histories/1.json
  def show
  end

  # GET /user/operation_histories/new
  def new
    @user_operation_history = User::OperationHistory.new
  end

  # GET /user/operation_histories/1/edit
  def edit
  end

  # POST /user/operation_histories
  # POST /user/operation_histories.json
  def create
    @user_operation_history = User::OperationHistory.new(user_operation_history_params)

    respond_to do |format|
      if @user_operation_history.save
        format.html { redirect_to @user_operation_history, notice: 'Operation history was successfully created.' }
        format.json { render :show, status: :created, location: @user_operation_history }
      else
        format.html { render :new }
        format.json { render json: @user_operation_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/operation_histories/1
  # PATCH/PUT /user/operation_histories/1.json
  def update
    respond_to do |format|
      if @user_operation_history.update(user_operation_history_params)
        format.html { redirect_to @user_operation_history, notice: 'Operation history was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_operation_history }
      else
        format.html { render :edit }
        format.json { render json: @user_operation_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/operation_histories/1
  # DELETE /user/operation_histories/1.json
  def destroy
    @user_operation_history.destroy
    respond_to do |format|
      format.html { redirect_to user_operation_histories_url, notice: 'Operation history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_operation_history
      @user_operation_history = User::OperationHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_operation_history_params
      params.require(:user_operation_history).permit(:user_id, :action_type, :note, :operated_at)
    end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_admin!

  # GET /users
  # GET /users.json
  def index
    @corporations = Corporation.all
    @users = User.all
  end

  def query
    @users =
      if params[:role] == 'all'
        User.all
      else
        User.where(role: params[:role])
      end
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new(corporation_id: params[:corporation_id])
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        User::OperationHistory.create(
          user: current_user,
          action_type: :create_account,
          note: "新增帳號：#{@user.name}，權限：#{@user.role}"
        )
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      old_name = @user.name
      old_role = @user.ch_role

      if @user.update(user_params)
        if 'password_digest'.in? @user.saved_changes
          User::OperationHistory.create(
            user: current_user,
            action_type: :change_password,
            note: "修改使用者 #{@user.name} 密碼"
          )
        end

        changes = []

        changes << "名稱 #{old_name} -> #{@user.name}" if 'name'.in? @user.saved_changes
        changes << "角色 #{old_role} -> #{@user.ch_role}" if 'role'.in? @user.saved_changes

        note = changes.join('，')

        if note.present?
          User::OperationHistory.create(
            user: current_user,
            action_type: :update,
            note: '修改使用者：' + note
          )
        end

        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User::OperationHistory.create!(
      user: current_user,
      action_type: :destroy,
      note: "刪除使用者：#{@user.name}"
    )

    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :corporation_id, :role)
  end
end

app/helpers/user/operation_histories_helper.rb
module User::OperationHistoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def role_options
    roles = User.roles.values

    roles = 
      if current_user.super_admin? || current_user.admin?
        roles.filter { |r| !r.in?(['admin', 'user']) }
      end

    roles.map { |r| [User::CH_ROLES_MAPPING[r], r] }
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, '使用者名稱' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password, '密碼' %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, '密碼確認' %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :corporation_id, '隸屬單位' %>
    <%= form.select :corporation_id, Corporation.all.map { |c| [c.name, c.id] } %>
  </div>

  <div class="field">
    <%= form.label :role, '角色' %>
    <%= form.select :role, role_options %>
  </div>

  <div class="actions">
    <%= form.submit '送出' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>編輯使用者</h1>

<%= render 'form', user: @user %>

<%= link_to '取消', users_path %>

app/views/users/index.html.erb
<h2>使用者角色管理</h2>

<h4>
  使用者群組列表
  <%= link_to '新增', new_corporation_path, class: 'btn btn-primary' %>
</h4>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>註冊單位</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @corporations.each do |corp| %>
      <tr>
        <td><%= corp.name %></td>
        <td>
          <%= link_to '編輯', edit_corporation_path(corp), class: 'btn btn-info' %>
          <%= link_to '刪除', corp, method: :delete, data: { confirm: '注意！執行刪除註冊單位時，若已有註冊使用者將同時被刪除，若要不影
響已存在的使用者，請用『編輯』修改資料，請確認是否仍要刪除該單位？' }, class: 'btn btn-danger' %>
          <%= link_to '註冊新使用者', new_user_path(corporation_id: corp.id), class: 'btn btn-outline-primary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr> 

<h4>使用者註冊資料</h4>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>名稱</th>
      <th>單位</th>
      <th>角色</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.corporation&.name %></td>
        <td><%= user.ch_role %></td>

        <td>
          <%= link_to '編輯', edit_user_path(user), class: 'btn btn-info' %>
          <%= link_to '刪除', user, method: :delete, data: { confirm: '確定刪除?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr> 

<%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<h1>新增使用者</h1>

<%= render 'form', user: @user %>

<%= link_to '取消', users_path %>

app/views/users/query.html.erb
<h1>帳號權限查詢</h1>

<%= form_with(url: query_users_url, method: :get, local: true) do |form| %>
  <%= form.select :role, [['全部', :all]].concat(role_options) %>
  <%= form.submit '查詢' %>
<% end %>
<p></p>
<%= render partial: 'shared/jtable_print_and_csv_export_links' %>

<table id="jTable" class="table">
  <thead class="thead-dark">
    <tr>
      <th>名稱</th>
      <th>單位</th>
      <th>角色</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.corporation&.name %></td>
        <td><%= user.ch_role %></td>

        <td>
          <%= link_to '編輯', edit_user_path(user), class: 'btn btn-info' %>
          <%= link_to '刪除', user, method: :delete, data: { confirm: '確定刪除?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr> 

<%= link_to 'Back', root_path %>

<%= render partial: 'shared/jtable_and_csv_export_js' %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Corporation:</strong>
  <%= @user.corporation.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.ch_role %>
</p>

<%= link_to '編輯', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>