config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#index'

  namespace :inspection do
    resources :results
    resources :histories do
      member do
        get 'pdf', as: :pdf
      end
    end
  end

  resources :areas do
    collection do
      get 'guide'
    end

    member do
      get 'map_image'
    end
  end
  resources :corporations

  resources :users do
    collection do
      get 'query'
    end
  end

  namespace :user do
    resources :operation_histories
  end

  namespace :equipment do
    resources :groups
    resources :components
    resources :meta_data do
      member do
        get 'download_pdf', as: :download_pdf
      end
    end
    resources :items do
      collection do
        get 'guide'
        get 'management'
        get 'create_inspection'
      end

      member do
        get 'map_image'
      end
      resources :inspection_histories, controller: '/inspection/histories'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'sign_in', to: 'sessions#new', as: :new_session
  post 'sign_in', to: 'sessions#create', as: :create_session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_session

  scope controller: :api, path: '/api', as: :api do
    get 'get_layer2' => :get_layer2, as: :get_layer2
    get 'get_equ_component' => :get_equ_component, as: :get_equ_component
  end

  get 'qrcode_download', to: 'qrcode_download#index', as: :qrcode_download
end

app/models/area.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: areas
#
#  id             :bigint           not null, primary key
#  map_image_data :text
#  name           :string
#  number         :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  category_id    :integer
#  owner_id       :bigint
#
# Indexes
#
#  index_areas_on_owner_id  (owner_id)
#
class Area < ApplicationRecord
  default_scope { order(id: :asc) }

  include MapImageUploader::Attachment(:map_image)

  has_many :equipment_items, class_name: 'Equipment::Item', dependent: :destroy
  has_many :sub_areas, class_name: 'Area', foreign_key: 'owner_id', dependent: :destroy

  belongs_to :category
  belongs_to :owner, class_name: 'Area', optional: true

  scope :layer1, -> { where(owner_id: nil) }
  scope :exclude_layer1, -> { where.not(id: layer1) }

  validates :name, uniqueness: { scope: [:owner] }

  delegate :layer1?, to: :category

  def hierachy
    has_owner? ? "#{owner&.name}-#{name}-#{number}" : name
  end

  def has_owner?
    owner_id.present?
  end

  def ch_type
    layer1? ? '工區' : '設施'
  end

  def equipment_components
    self.class.includes(sub_areas: [:equipment_items])
    if layer1?
      sub_areas.includes(equipment_items: [meta_datum: :component]).map(&:equipment_items).flatten.map(&:component).uniq
    else
      equipment_items.includes(meta_datum: :component).map(&:component).uniq
    end
  end
end

app/models/area/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: area_categories
#
#  id           :bigint           not null, primary key
#  code         :string
#  english_name :string
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Area::Category < ApplicationRecord
  LAYER1 = [
    { name: '石門', english_name: 'Shihmen', code: 'Sm' },
    { name: '中庄', english_name: 'Zhongzhuang', code: 'Zh' },
    { name: '羅東', english_name: 'Luodong', code: 'Ld' },
    { name: '榮華', english_name: 'Ronghua', code: 'Rh' },
    { name: '義興', english_name: 'Yising', code: 'Ys' },
    { name: '隆恩', english_name: 'Lungen', code: 'Le' },
    { name: '上坪', english_name: 'Shangping', code: 'Sp' },
    { name: '寶山第二水庫', english_name: 'Baoshan Second', code: 'BS' },
    { name: '桃園大圳', english_name: 'Taoyuan', code: 'Ty' },
    { name: '阿姆坪防淤隧道', english_name: 'Amuping', code: 'Am' },
    { name: '大灣坪防淤隧道', english_name: 'Dawanping', code: 'Dw' }
  ].freeze

  before_save :upcase_code

  has_many :areas, dependent: :destroy

  scope :layer1, -> { where(name: LAYER1.map { |layer1_category| layer1_category[:name] }) }
  scope :selectable, -> { where.not(id: layer1) }

  def layer1?
    name.in?(LAYER1.map { |category| category[:name] }) ||
      Area.find_by(name: name).present?
  end

  private

    def upcase_code
      code.upcase!
    end
end

app/controllers/areas_controller.rb
# frozen_string_literal: true

class AreasController < ApplicationController
  before_action :set_area, only: %i[show edit update destroy]
  before_action :authenticate_admin!, except: %i[guide index map_image]

  # GET /areas
  # GET /areas.json
  def index
    if params[:get_equ_options] && params[:layer2_area_id] && params[:layer1_area_id]
      options = 
        if params[:layer2_area_id].to_i.zero?
          Area.find(params[:layer1_area_id]).equipment_components
        else
          Area.find(params[:layer2_area_id]).equipment_components
        end
      render(json: options) && return
    end

    if params[:get_options] && params[:layer1_area_id]
      area1 = Area.find(params[:layer1_area_id])

      render(json: { 
        layer2: Area.select(:id, :name).where(owner: area1),
        equipment_components: area1.equipment_components
      }) && return
    end

    if params[:get_full_data] && params[:layer1_area_id] && params[:layer2_area_id]
      if params[:layer2_area_id].to_i == 0
        render(json: Area.where(owner_id: params[:layer1_area_id]).map do |area|
          {
            name: area.name,
            owner: area.owner&.name,
            map_image_url: area.map_image_url ? map_image_area_url(area) : nil
          }
        end) && return
      else
        area = Area.find(params[:layer2_area_id])
        render(json: [{ name: area.name, owner: area.owner&.name, map_image_url: area.map_image_url ? map_image_area_url(area) : nil }]) && return
      end
    end

    @layer1_areas = Area.layer1
    @other_areas = Area.includes(:owner).where.not(id: @layer1_areas)
  end

  def guide
    @layer1_areas = Area.select(:id, :name, :category_id).layer1
    @layer2_areas = Area.select(:id, :name, :category_id).where(owner_id: @layer1_areas.first.id)
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: { name: @area.name, owner: @area.owner&.name, map_image_url: @area.map_image_url } }
    end
  end

  # GET /areas/new
  def new
    @area = Area.new
    @has_owner = params[:has_owner]
  end

  # GET /areas/1/edit
  def edit; end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    if params[:area][:english_name] && params[:area][:code]
      category = Area::Category.create(
        name: params[:area][:name],
        english_name: params[:area][:english_name],
        code: params[:area][:code]
      )

      @area.category = category
    end

    respond_to do |format|
      if @area.save
        note = if @area.layer1?
                 "新增工區：#{@area.name}"
               else
                 "新增設施：#{@area.owner&.name}-#{@area.name}"
               end

        User::OperationHistory.create(
          user: current_user,
          action_type: 'create',
          note: note
        )

        format.html { redirect_to areas_url, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    render 'edit' and return unless params[:area]

    note = if @area.layer1?
             '修改工區：'
           else
             '修改設施：'
           end

    note += @area.hierachy

    respond_to do |format|
      if @area.update(area_params)
        if %w[name owner_id number].any? { |column| column.in? @area.saved_changes.keys }
          note += ' -> '
          note += @area.hierachy

          User::OperationHistory.create(
            user: current_user,
            action_type: :update,
            note: note
          )
        end

        if ['map_image_data'].in? @area.saved_changes.keys
          note.concat += "更新 #{@area.hierachy} 的地圖"

          User::OperationHistory.create(
            user: current_user,
            action_type: :upload_image,
            note: note
          )
        end

        format.html { redirect_to edit_area_path(@area), notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit, notice: 'Update Failed!!!!!' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    hierachy = @area.hierachy
    ch_type = @area.ch_type

    @area.destroy

    User::OperationHistory.create(
      user: current_user,
      action_type: :destroy,
      note: "刪除#{ch_type}：#{hierachy}"
    )
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_map
    @area = Area.find(params[:area_id])
    @area.update(map_image: nil)

    redirect_to edit_area_path(@area)
  end

  def map_image
    area = Area.find(params[:id])

    redirect_to area.map_image_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_area
    @area = Area.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def area_params
    params.require(:area).permit(:name, :number, :category_id, :owner_id, :map_image)
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
        <% area.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if area.category&.layer1? %>
    <p>
      <strong>工區名稱:</strong>
      <%= @area.name %>
    </p>

    <p>
      <strong>工區代碼:</strong>
      <%= "#{@area.category.code}" %>
    </p>

  <% else %>
    <% if @has_owner || action_name == 'edit' %>
      <div class="field">
        <% name = action_name == 'edit' ? '編輯設施名稱' : '新增設施名稱' %>
        <%= form.label :name, name %>
        <%= form.text_field :name %>
      </div>


      <div class="field">
        <%= form.label :owner_id, '設定隸屬工區' %>
        <%= form.select :owner_id, Area.layer1.map{ |a| [a.name, a.id] } %>
      </div>

      <div class="field">
        <%= form.label :category_id, '定義設施屬性' %>
        <%= form.select :category_id, Area::Category.selectable.map { |c| [c.name, c.id] } %>
      </div>

      <div class="field">
        <% number = action_name == 'edit' ? '編輯設施序號' : '新增設施序號' %>
        <%= form.label :number, '新增設施序號' %>
        <%= form.select :number, 0..9 %>
      </div>
    <% else %>
      <div class="field">
        <%= form.label :name, '工區名稱' %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :english_name, '英文名稱' %>
        <%= form.text_field :english_name %>
      </div>

      <div class="field">
        <%= form.label :code, '工區代碼' %>
        <%= form.text_field :code %>
      </div>
    <% end %>
  <% end %>

  <div class="field">
    <%= form.label :map_image, '上傳設施地圖', value: area.cached_map_image_data %>
    <%= form.file_field :map_image %>
    <% if area.map_image %>
      <div>
        <%= link_to '顯示原圖', area.map_image_url, class: 'btn btn-dark ', target: '_blank' %><br>
        <%= image_tag area.map_image_url, width: 500 %>
      </div>
    <% end %>
    <br>
  </div>

  <div class="actions">
    <% btn_name = action_name == 'edit' ? '確認更新' : '確定新增' %>
    <%= form.submit '確定新增' %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>編輯設施設定</h1>

<%= render 'form', area: @area %>

<%= link_to '內容', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/guide.html.erb
<h1>工區地圖導覽</h1>

<div id="guide-app">
  
  <div id="divDropdown" class="dropdown">
    工區：<select size="1" id="optArea1" v-model="layer1Selected">
      <option v-for="option in layer1Options" :value="option.id">
        {{ option.name }}
      </option>
    </select>

    &emsp;設施安裝位置：<select size="1" id="optArea2" v-model="layer2Selected">
      <option v-for="option in layer2Options" :value="option.id">
        {{ option.name }}
      </option>
    </select>

    <input @click="getAreas" type="button" value="篩選" id="btnSendResult" name="B1">
  </div>

  <p></p>

  <%= render partial: 'shared/jtable_print_and_csv_export_links' %>
  <table id="jTable" class="table">
    <thead class="thead-dark">
      <tr>
        <th>設施安裝位置</th>
        <th>隸屬工區</th>
        <th>功能列</th>
      </tr>
    </thead>

    <tbody>
    <template v-if="targetItems.length > 0">
      <tr v-for="targetItem in targetItems">
        <td>{{ targetItem.name }}</td>
        <td>{{ targetItem.owner }}</td>

        <td v-if="targetItem.map_image_url">
          <a class="btn btn-info" :href="targetItem.map_image_url" onclick="window.open(this.href, '', 'width=800,height=600, location=no,toolbar=no'); return false;">檢視地圖</a>
          <a class="btn btn-dark" :href="qrcodeDownloadUrl(targetItem.map_image_url)">地圖QR Code下載</a>
        </td>
        <td v-else></td>
      </tr>
    </template>
    </tbody>
  </table>
</div>

<script>
var vueApp = true
</script>

<%= render partial: 'shared/jtable_and_csv_export_js' %>

<script>
new Vue({
  el: '#guide-app',
  data: {
    layer1Options: <%= raw json_escape(@layer1_areas.to_json) %>,
    layer2Options: [{ name: '全部', id: 0 }].concat(<%= raw json_escape(@layer2_areas.to_json) %>),
    layer1Selected: <%= @layer1_areas.first.id %>,
    layer2Selected: 0,
    targetItems: []
  },

  watch: {
    layer1Selected: function(newVal) {
      const self = this
      axios.get("<%= areas_path %>" + '?get_options=true&layer1_area_id=' + this.layer1Selected)
        .then(function(res) {
          self.layer2Options = [{ name: '全部', id: 0 }].concat(res.data.layer2)
          self.layer2Selected = 0
        })
    }
  },

  mounted: function() {
    bindExportBtn()
    bindPrintBtn()
  },

  methods: {
    getAreas: function() {
      if (jTable) {
        jTable.destroy()
      }

      const self = this

      axios.get("<%= areas_path %>" + '?get_full_data=true&&layer1_area_id=' + this.layer1Selected + '&layer2_area_id=' + this.layer2Selected)
        .then(function(res) { self.targetItems = res.data })
        .then(function() { self.$nextTick(initDataTable()) })
    },

    qrcodeDownloadUrl: function(targetUrl) {
      return '/qrcode_download?target_url=' + targetUrl
    }
  }
})
</script>

app/views/areas/index.html.erb
<h1>工區資訊管理</h1>
<br>
<br>
<h2>
  工區名稱
  <%= link_to '新增工區', new_area_path, class: 'btn btn-primary' %>
</h2>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th> 名稱</th>
      <th colspan="3">功能列</th>
    </tr>
  </thead>

  <tbody>
    <% @layer1_areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= link_to '內容', area, class: 'btn btn-outline-dark' %></td>
        <td><%= link_to '編輯', edit_area_path(area), class: 'btn btn-info' %></td>
        <td><%= link_to '刪除', area, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<h2>
  設備安裝位置
  <%= link_to '新增安裝位置', new_area_path(has_owner: true), class: 'btn btn-primary' %>
</h2>
<p></p>
<%= render partial: 'shared/jtable_print_and_csv_export_links' %>

<table id="jTable" class="table">
  <thead class="thead-dark">
    <tr>
      <th>安裝位置</th>
      <th>隸屬工區</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @other_areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= area.owner&.name %></td>
        <td><%= link_to '內容', area, class: 'btn btn-outline-dark' %>
        <%= link_to '編輯', edit_area_path(area), class: 'btn btn-info' %>
        <%= link_to '刪除', area, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= render partial: 'shared/jtable_and_csv_export_js' %>

app/views/areas/new.html.erb
<h1>
  <% if @has_owner %>
    新增設施設定
  <% else %>
    新增工區設定
  <% end %>
</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path, class: 'btn btn-primary' %>

app/views/areas/show.html.erb
<% if @area.layer1? %>
  <p>
    <strong>工區名稱:</strong>
    <%= "#{@area.name}(#{@area.category&.english_name})" %>
  </p>

  <p>
    <strong>工區代碼:</strong>
    <%= @area.category.code %>
  </p>

  <p>
    <strong>地圖:</strong>
    <% if @area.map_image %>
      <%= image_tag @area.map_image_url, width: 500 %>
    <% end %>
  </p>
<% else %>
  <p>
    <strong>設施名稱:</strong>
    <%= @area.name %>
  </p>

  <p>
    <strong>設施類型:</strong>
    <%= "#{@area.category.name}(#{@area.category.code})" %>
  </p>

  <p>
    <strong>設施編號:</strong>
    <%= "#{@area.number}" %>
  </p>

  <p>
    <strong>隸屬工區:</strong>
    <%= @area.owner&.name %>
  </p>

  <p>
    <strong>地圖:</strong>
    <% if @area.map_image %>
      <%= image_tag @area.map_image_url, width: 500 %>
    <% end %>
  </p>
<% end %>
<%= link_to '編輯', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>