config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#index'

  namespace :inspection do
    resources :results
    resources :histories do
      member do
        get 'pdf', as: :pdf
      end
    end
  end

  resources :areas do
    collection do
      get 'guide'
    end

    member do
      get 'map_image'
    end
  end
  resources :corporations

  resources :users do
    collection do
      get 'query'
    end
  end

  namespace :user do
    resources :operation_histories
  end

  namespace :equipment do
    resources :groups
    resources :components
    resources :meta_data do
      member do
        get 'download_pdf', as: :download_pdf
      end
    end
    resources :items do
      collection do
        get 'guide'
        get 'management'
        get 'create_inspection'
      end

      member do
        get 'map_image'
      end
      resources :inspection_histories, controller: '/inspection/histories'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'sign_in', to: 'sessions#new', as: :new_session
  post 'sign_in', to: 'sessions#create', as: :create_session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_session

  scope controller: :api, path: '/api', as: :api do
    get 'get_layer2' => :get_layer2, as: :get_layer2
    get 'get_equ_component' => :get_equ_component, as: :get_equ_component
  end

  get 'qrcode_download', to: 'qrcode_download#index', as: :qrcode_download
end

app/models/equipment.rb
module Equipment
  def self.table_name_prefix
    'equipment_'
  end
end

app/models/equipment/component.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: equipment_components
#
#  id                   :bigint           not null, primary key
#  code                 :string
#  english_name         :string
#  inspection_form_name :string
#  name                 :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
class Equipment::Component < ApplicationRecord
  has_many :meta_data, dependent: :destroy
  has_many :items, through: :meta_data
  has_many :inspection_histories, through: :items

  def hierachy
    "#{name}(#{code})-#{inspection_form_name}"
  end

  def inspection_form
    Inspection::Form.find_by(name: inspection_form_name) if inspection_form_name
  end

  def layer2_areas
    items.includes(:area).map(&:area).uniq
  end
end

app/models/equipment/meta_datum.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: equipment_meta_data
#
#  id           :bigint           not null, primary key
#  company      :string
#  equ_model    :string
#  fc_para_data :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  component_id :bigint
#
# Indexes
#
#  index_equipment_meta_data_on_component_id  (component_id)
#
class Equipment::MetaDatum < ApplicationRecord
  include EquipmentFcParaUploader::Attachment(:fc_para)

  belongs_to :component, inverse_of: :meta_data

  has_many :items, dependent: :destroy

  def hierachy
    [
      component.name,
      company,
      equ_model
    ].join('-')
  end

  def fc_para_filename
    fc_para && fc_para.id.split('/')[2]
  end
end

app/controllers/equipment/components_controller.rb
# frozen_string_literal: true

class Equipment::ComponentsController < ApplicationController
  before_action :set_equipment_component, only: %i[show edit update destroy]

  # GET /equipment/components
  # GET /equipment/components.json
  def index
    @equipment_components = Equipment::Component.all
  end

  # GET /equipment/components/1
  # GET /equipment/components/1.json
  def show
    @meta_data = @equipment_component.meta_data
    @equipment_items = @equipment_component.items.includes(:area)
  end

  # GET /equipment/components/new
  def new
    @equipment_component = Equipment::Component.new
  end

  # GET /equipment/components/1/edit
  def edit; end

  # POST /equipment/components
  # POST /equipment/components.json
  def create
    @equipment_component = Equipment::Component.new(equipment_component_params)

    respond_to do |format|
      if @equipment_component.save

        User::OperationHistory.create(
          user: current_user,
          action_type: 'create',
          note: "新增設備：#{@equipment_component.hierachy}"
        )

        format.html do
          redirect_to equipment_components_url,
                      notice: 'Component was successfully created.'
        end
        format.json { render :show, status: :created, location: @equipment_component }
      else
        format.html { render :new }
        format.json { render json: @equipment_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/components/1
  # PATCH/PUT /equipment/components/1.json
  def update
    old_hierachy = @equipment_component.hierachy

    respond_to do |format|
      User::OperationHistory.create(
        user: current_user,
        action_type: :update,
        note: "修改設備：#{old_hierachy} -> #{@equipment_component.hierachy}"
      )

      if @equipment_component.update(equipment_component_params)
        format.html do
          redirect_to @equipment_component, notice: 'Component was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @equipment_component }
      else
        format.html { render :edit }
        format.json { render json: @equipment_component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/components/1
  # DELETE /equipment/components/1.json
  def destroy
    hierachy = @equipment_component.hierachy
    @equipment_component.destroy

    User::OperationHistory.create(
      user: current_user,
      action_type: :destroy,
      note: "刪除設備組件：#{hierachy}"
    )
    respond_to do |format|
      format.html do
        redirect_to equipment_components_url, notice: 'Component was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_equipment_component
    @equipment_component = Equipment::Component.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def equipment_component_params
    params.require(:equipment_component).permit(:group_id, :name, :code, :inspection_form_name)
  end
end

app/controllers/equipment/items_controller.rb
# frozen_string_literal: true

class Equipment::ItemsController < ApplicationController
  ALL_ID = 9999

  before_action :set_equipment_item, only: %i[show edit update destroy]
  before_action :authenticate_admin!, except: %i[guide index create_inspection]

  # GET /equipment/items
  # GET /equipment/items.json
  def index
    if params[:get_full_data]
      area = Area.find(params[:layer1_area_id])
      equ_items = 
        if params[:layer2_area_id].to_i.zero?
          area.sub_areas.map(&:equipment_items).flatten.uniq
        else
          area.sub_areas.find_by(id: params[:layer2_area_id]).equipment_items
        end

      unless params[:equ_component_id].to_i.zero?
        equ_items = equ_items.filter { |item| item.component.id == params[:equ_component_id].to_i }
      end

      render json: equ_items.map { |item|
        {
          id: item.id,
          component_name: item.component.name,
          layer1: item.area.owner.name,
          layer2: item.area.name,
          display_name: item.display_name,
          model: item.meta_datum.equ_model,
          has_fc_para: item.meta_datum.fc_para&.exists?,
          download_fc_para_url: download_pdf_equipment_meta_datum_path(item.meta_datum),
          map_image_url: item.map_image_url ? (root_url + item.map_image_url).gsub('//', '/').gsub(':/', '://') : nil
        }
      } and return
    end

    if params[:layer1_area_id] && params[:layer2_area_id] && params[:equ_component_id]
      equ_items =
        if params[:layer2_area_id].to_i == ALL_ID
          Area.includes(:equipment_items).find(params[:layer1_area_id]).sub_areas.map(&:equipment_items).flatten.uniq
        else
          Area.find(params[:layer2_area_id]).equipment_items.includes(:area, meta_datum: :component)
        end

      if params[:equ_component_id].to_i != ALL_ID
        equ_items = equ_items.filter do |item| 
          item.component.id == params[:equ_component_id].to_i
        end
      end

      render json: equ_items.map { |item|
        {
          id: item.id,
          component_name: item.component.name,
          layer1: item.area.owner.name,
          layer2: item.area.name,
          display_name: item.display_name,
          model: item.meta_datum.equ_model,
          has_fc_para: item.meta_datum.fc_para&.exists?,
          download_fc_para_url: download_pdf_equipment_meta_datum_path(item.meta_datum),
          map_image_url: item.map_image_url ? (root_url + item.map_image_url).gsub('//', '/').gsub(':/', '://') : nil
        }
      } and return
    end

    @equipment_items = Equipment::Item.all
  end

  def create_inspection
    @layer1_areas = Area.select(:id, :name, :category_id).layer1
  end

  def guide
    @layer1_areas = Area.select(:id, :name, :category_id).layer1
    @layer2_areas = Area.select(:id, :name, :category_id).where(owner_id: @layer1_areas.first.id)
    @equ_components = @layer2_areas.map(&:equipment_components).flatten.uniq
  end

  def map_image
    item = Equipment::Item.find(params[:id])

    redirect_to item.map_image_url
  end

  def management
    @layer1_areas = Area.select(:id, :name, :category_id).layer1
    @layer2_areas = Area.select(:id, :name, :category_id).where(owner_id: @layer1_areas.first.id)
    @equ_components = @layer2_areas.map(&:equipment_components).flatten.uniq
  end

  # GET /equipment/items/1
  # GET /equipment/items/1.json
  def show
    cookies[:inspection_form_back_path] = request.path
    @inspection_histories = @equipment_item.inspection_histories
  end

  # GET /equipment/items/new
  def new
    @equipment_item =
      if params[:meta_datum_id]
        Equipment::MetaDatum.find(params[:meta_datum_id]).items.build
      else
        Equipment::Item.new
      end
  end

  # GET /equipment/items/1/edit
  def edit; end

  # POST /equipment/items
  # POST /equipment/items.json
  def create
    @equipment_item = Equipment::Item.new(equipment_item_params)

    render('new', equipment_item: @equipment_item) && return if params[:display_name]

    respond_to do |format|
      if @equipment_item.save
        User::OperationHistory.create!(
          user: current_user,
          action_type: :create,
          note: "新增設備：#{@equipment_item.display_name}"
        )
        format.html { redirect_to @equipment_item.component, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @equipment_item }
      else
        format.html { render :new }
        format.json { render json: @equipment_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/items/1
  # PATCH/PUT /equipment/items/1.json
  def update
    if params[:display_name]
      @equipment_item.assign_attributes(equipment_item_params)
      render('edit', equipment_item: @equipment_item) && return
    end

    respond_to do |format|
      old_display_name = @equipment_item.display_name

      if @equipment_item.update(equipment_item_params)
        if old_display_name != @equipment_item.display_name
          User::OperationHistory.create!(
            user: current_user,
            action_type: :update,
            note: "修改設備：#{old_display_name} -> #{@equipment_item.display_name}"
          )
        end

        if 'map_image_data'.in? @equipment_item.saved_changes.keys
          User::OperationHistory.create!(
            user: current_user,
            action_type: :upload_image,
            note: "更新 #{@equipment_item.display_name} 的地圖"
          )
        end

        format.html { redirect_to @equipment_item.component, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment_item }
      else
        format.html { render :edit }
        format.json { render json: @equipment_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/items/1
  # DELETE /equipment/items/1.json
  def destroy
    User::OperationHistory.create!(
      user: current_user,
      action_type: :destroy,
      note: "刪除設備：#{@equipment_item.display_name}"
    )
    @equipment_item.destroy
    respond_to do |format|
      format.html { redirect_to @equipment_item.component, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_equipment_item
    @equipment_item = Equipment::Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def equipment_item_params
    params.require(:equipment_item).permit(:meta_datum_id, :area_id, :name, :direction_code, :map_image, :note)
  end
end

app/controllers/equipment/meta_data_controller.rb
# frozen_string_literal: true

class Equipment::MetaDataController < ApplicationController
  before_action :set_equipment_meta_datum, only: %i[show download_pdf edit update destroy]

  # GET /equipment/meta_data
  # GET /equipment/meta_data.json
  def index
    @equipment_meta_data = Equipment::MetaDatum.all
  end

  # GET /equipment/meta_data/1
  # GET /equipment/meta_data/1.json
  def show; end

  def download_pdf
    send_data @equipment_meta_datum.fc_para.read, filename: "#{@equipment_meta_datum.equ_model}.pdf"
  end

  # GET /equipment/meta_data/new
  def new
    @equipment_meta_datum = if params[:component_id]
                              Equipment::Component.find(params[:component_id]).meta_data.build
                            else
                              Equipment::MetaDatum.new
                            end
  end

  # GET /equipment/meta_data/1/edit
  def edit; end

  # POST /equipment/meta_data
  # POST /equipment/meta_data.json
  def create
    @equipment_meta_datum = Equipment::MetaDatum.new(equipment_meta_datum_params)

    respond_to do |format|
      if @equipment_meta_datum.save

        User::OperationHistory.create!(
          user: current_user,
          action_type: :create,
          note: "新增設備資訊：#{@equipment_meta_datum.hierachy}"
        )

        format.html { redirect_to @equipment_meta_datum.component, notice: 'Meta datum was successfully created.' }
        format.json { render :show, status: :created, location: @equipment_meta_datum }
      else
        format.html { render :new }
        format.json { render json: @equipment_meta_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/meta_data/1
  # PATCH/PUT /equipment/meta_data/1.json
  def update
    old_hierachy = @equipment_meta_datum.hierachy

    respond_to do |format|
      if @equipment_meta_datum.update(equipment_meta_datum_params)
        if old_hierachy != @equipment_meta_datum.hierachy
          User::OperationHistory.create(
            user: current_user,
            action_type: :update,
            note: "修改設備資訊：#{old_hierachy} -> #{@equipment_meta_datum.hierachy}"
          )
        end

        if 'fc_para_data'.in?(@equipment_meta_datum.saved_changes.keys)
          User::OperationHistory.create(
            user: current_user,
            action_type: :upload_image,
            note: "更新 #{@equipment_meta_datum.hierachy} 的設備資訊手冊"
          )
        end

        format.html { redirect_to @equipment_meta_datum.component, notice: 'Meta datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment_meta_datum }
      else
        format.html { render :edit }
        format.json { render json: @equipment_meta_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/meta_data/1
  # DELETE /equipment/meta_data/1.json
  def destroy
    component = @equipment_meta_datum.component
    hierachy = @equipment_meta_datum.hierachy

    @equipment_meta_datum.destroy

    User::OperationHistory.create(
      user: current_user,
      action_type: :destroy,
      note: "刪除設備資訊：#{hierachy}"
    )
    respond_to do |format|
      format.html { redirect_to component, notice: 'Meta datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_equipment_meta_datum
    @equipment_meta_datum = Equipment::MetaDatum.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def equipment_meta_datum_params
    params.require(:equipment_meta_datum).permit(:component_id, :company, :equ_model, :fc_para)
  end
end

app/helpers/equipment/components_helper.rb
module Equipment::ComponentsHelper
end

app/helpers/equipment/items_helper.rb
# frozen_string_literal: true

module Equipment::ItemsHelper
end

app/helpers/equipment/meta_data_helper.rb
module Equipment::MetaDataHelper
end

app/views/equipment/items/_form.html.erb
<%= form_with(model: equipment_item, local: true) do |form| %>
  <% if equipment_item.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% equipment_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meta_datum_id, '廠牌名稱' %>
    <%= form.hidden_field :meta_datum_id, value: equipment_item.meta_datum.id, 'v-model': 'meta_datum_id' %>
    <%= equipment_item.meta_datum.company %>
  </div>

  <div class="field">
    <%= form.label :meta_datum_id, '設備型號' %>
    <%= equipment_item.meta_datum.equ_model %>
  </div>

  <div class="field" id="area-app">
    <%= form.label :area_id, '選擇安裝位置' %>

    <select size="1" id="optArea1" v-model="layer1Selected">
      <option v-for="option in layer1Options" :value="option.id">
        {{ option.name }}
      </option>
    </select>
    <select name="equipment_item[area_id]" id="equipment_item_area_id" v-model="layer2Selected">
      <option v-for="option in layer2Options" :value="option.id">
        {{option.name}}
      </option>
    </select>
  </div>

  <div class="field">
    <%= form.label :name, '設備序號' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :direction_code, '臨時碼' %>
    <%= form.text_field :direction_code %>（選填）
  </div>

  <div class="field">
    <%= form.label :note, '臨時碼說明欄' %>
    <%= form.text_field :note %>
  </div>

  <div class="field">
    <%= form.label :display_name, '設備編碼' %>
    <%= form.button '產生編碼', { name: 'display_name' } %>
    <%= equipment_item.display_name if equipment_item.display_name_generatable? %>
  </div>

  <div class="field">
    <%= form.label :map_image, '上傳設備位置地圖' %>
    <%= form.file_field :map_image %><br>
    <% if equipment_item.map_image %>
      <%= image_tag equipment_item.map_image_url, width: 500 %>
    <% end %><br>
  </div>

  <div class="actions">
    <%= form.submit '確認註冊' %>
  </div>
<% end %>

<script>
<% 
  first_layer1 = Area.layer1.first
  layer2 = equipment_item.area || first_layer1.sub_areas.first
  layer1 = layer2&.owner || first_layer1
%>
new Vue({
  el: '#area-app',
  data: {
    layer1Options: <%= raw json_escape(Area.layer1.to_json) %>,
    layer2Options: <%= raw json_escape((layer1.sub_areas).to_json) %>,
    layer1Selected: <%= layer1&.id || first_layer1.id %>,
    layer2Selected: <%= layer2&.id || 0 %>
  },
  watch: {
    layer1Selected: function(newVal) {
      const self = this
      axios.get("<%= areas_path %>" + '?get_options=true&layer1_area_id=' + this.layer1Selected)
        .then(function(res) {
          self.layer2Options = res.data.layer2
          self.layer2Selected = res.data.layer2[0] ? res.data.layer2[0].id : self.layer2Selected
        })
    }
  }
})
</script>

app/views/equipment/items/edit.html.erb
<h1>編輯設備</h1>

<%= render 'form', equipment_item: @equipment_item %>

<%= link_to '取消', @equipment_item.component %>

app/views/equipment/items/guide.html.erb
<h1>設備安裝位置地圖導覽</h1>

<div id="guide-app">
  
  工區：<div id="divDropdown" class="dropdown">
    <select size="1" id="optArea1" v-model="layer1Selected">
      <option v-for="option in layer1Options" :value="option.id">
        {{ option.name }}
      </option>
    </select>

    &emsp;設施安裝位置：<select size="1" id="optArea2" v-model="layer2Selected">
      <option v-for="option in layer2Options" :value="option.id">
        {{ option.name }}
      </option>
    </select>

    &emsp;設備類別：<select size="1" id="optEq" v-model="equComponentSelected">
      <option v-for="option in equComponentOptions" :value="option.id">
        {{ option.name }}
      </option>
    </select>

    <input @click="getEquItems" type="button" value="篩選" id="btnSendResult" name="B1">
  </div>

  <p></p>

  <%= render partial: 'shared/jtable_print_and_csv_export_links' %>
  <table id="jTable" class="table">
    <thead class="thead-dark">
      <tr>
        <th>設備類型</th>
        <th>工區名稱</th>
        <th>設備安裝位置</th>
        <th>設備註冊碼</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    <template v-if="targetItems.length > 0">
      <tr v-for="targetItem in targetItems">
        <td>{{ targetItem.component_name }}</td>
        <td>{{ targetItem.layer1 }}</td>
        <td>{{ targetItem.layer2 }}</td>
        <td>{{ targetItem.display_name }}</td>

        <td v-if="targetItem.map_image_url">
          <a class="btn btn-info" :href="targetItem.map_image_url" onclick="window.open(this.href, '', 'width=800,height=600, location=no,toolbar=no'); return false;">檢視安裝點地圖</a>
        </td>
        <td v-else>
        </td>
      </tr>
    </template>
    </tbody>
  </table>
</div>

<script>
var vueApp = true
</script>

<%= render partial: 'shared/jtable_and_csv_export_js' %>

<script>
new Vue({
  el: '#guide-app',
  data: {
    layer1Options: <%= raw json_escape(@layer1_areas.to_json) %>,
    layer2Options: [{ name: '全部', id: 0 }].concat(<%= raw json_escape(@layer2_areas.to_json) %>),
    equComponentOptions: [{ name: '全部', id: 0 }].concat(<%= raw json_escape(@equ_components.to_json) %>),
    layer1Selected: <%= @layer1_areas.first.id %>,
    layer2Selected: 0,
    equComponentSelected: 0,
    targetItems: []
  },

  mounted: function() {
    bindExportBtn()
    bindPrintBtn()
  },

  watch: {
    layer1Selected: function(newVal) {
      const self = this
      axios.get("<%= areas_path %>" + '?get_options=true&layer1_area_id=' + this.layer1Selected)
        .then(function(res) {
          console.log(res)
          self.layer2Options = [{ name: '全部', id: 0 }].concat(res.data.layer2)
          self.equComponentOptions = [{ name: '全部', id: 0 }].concat(res.data.equipment_components)
          self.layer2Selected = 0
          self.equComponentSelected = 0
        })
    },

    layer2Selected: function(newVal) {
      const self = this

      self.equComponentOptions = [{ name: '全部', id: 0 }]
      self.equComponentSelected = 0

      axios.get("<%= areas_path %>" + '?get_equ_options=true&layer1_area_id='+ this.layer1Selected + '&layer2_area_id=' + this.layer2Selected)
        .then(function(res) {
          self.equComponentOptions = [{ name: '全部', id: 0 }].concat(res.data)
        })
    }
  },

  methods: {
    getEquItems: function() {
      if (jTable) {
        jTable.destroy()
      }

      const self = this

      axios.get("<%= equipment_items_path %>" + '?get_full_data=true&layer1_area_id=' + this.layer1Selected + '&layer2_area_id=' + this.layer2Selected + '&equ_component_id=' + this.equComponentSelected)
        .then(function(res) { self.targetItems = res.data })
        .then(function() { self.$nextTick(initDataTable()) })
    },

    qrcodeDownloadUrl: function(targetUrl) {
      return '/qrcode_download?target_url=' + targetUrl
    }
  }
})
</script>

app/views/equipment/items/index.html.erb
<h1>Equipment Items</h1>

<table>
  <thead>
    <tr>
      <th>Metadata</th>
      <th>Area</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment_items.each do |equipment_item| %>
      <tr>
        <td><%= equipment_item.metadata_id %></td>
        <td><%= equipment_item.area_id %></td>
        <td><%= equipment_item.name %></td>
        <td><%= link_to '內容', equipment_item %></td>
        <td><%= link_to '編輯', edit_equipment_item_path(equipment_item) %></td>
        <td><%= link_to '刪除', equipment_item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipment Item', new_equipment_item_path %>

app/views/equipment/items/new.html.erb
<h1>設備註冊</h1>

<%= render 'form', equipment_item: @equipment_item %>

<%= link_to '取消', @equipment_item.component %>

app/views/equipment/items/show.html.erb
<p>
  <strong>公司:</strong>
  <%= @equipment_item.meta_datum.company %>
</p>

<p>
  <strong>Area:</strong>
  <%= @equipment_item.area.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= "#{@equipment_item.component.name}-#{@equipment_item.name}" %>
</p>

<p>
  <strong>QR Code</strong><br><br>
  <%== qrcode(new_equipment_item_inspection_history_url(@equipment_item)) %>

  <%= link_to '下載 QRCode', qrcode_download_path(target_url: new_equipment_item_inspection_history_url(@equipment_item)) %>
</p>

<h3>巡檢歷史紀錄</h3>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>類型</th>
      <th>第幾次</th>
      <th>年度</th>
      <th>上傳時間</th>
      <th>編輯</th>
      <th>結果</th>
    </tr>
  </thead>
  <tbody>
    <% @inspection_histories.each do |history| %>
      <tr>
        <td><%= history.maintain_type %></td>
        <td><%= history.serial_number %></td>
        <td><%= history.year %></td>
        <td><%= history.uploaded_at %></td>
        <td><%= link_to '編輯', edit_inspection_history_path(history) %></td>
        <td><%= link_to '查看結果', equipment_item_inspection_history_path(@equipment_item, history) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '開始巡檢', new_equipment_item_inspection_history_path(@equipment_item), target: '_blank' %> |
<%= link_to '編輯', edit_equipment_item_path(@equipment_item) %> |
<%= link_to 'Back', equipment_component_path(@equipment_item.component) %>