config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#index'

  namespace :inspection do
    resources :results
    resources :histories do
      member do
        get 'pdf', as: :pdf
      end
    end
  end

  resources :areas do
    collection do
      get 'guide'
    end

    member do
      get 'map_image'
    end
  end
  resources :corporations

  resources :users do
    collection do
      get 'query'
    end
  end

  namespace :user do
    resources :operation_histories
  end

  namespace :equipment do
    resources :groups
    resources :components
    resources :meta_data do
      member do
        get 'download_pdf', as: :download_pdf
      end
    end
    resources :items do
      collection do
        get 'guide'
        get 'management'
        get 'create_inspection'
      end

      member do
        get 'map_image'
      end
      resources :inspection_histories, controller: '/inspection/histories'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  get 'sign_in', to: 'sessions#new', as: :new_session
  post 'sign_in', to: 'sessions#create', as: :create_session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_session

  scope controller: :api, path: '/api', as: :api do
    get 'get_layer2' => :get_layer2, as: :get_layer2
    get 'get_equ_component' => :get_equ_component, as: :get_equ_component
  end

  get 'qrcode_download', to: 'qrcode_download#index', as: :qrcode_download
end

app/models/inspection.rb
module Inspection
  def self.table_name_prefix
    'inspection_'
  end
end

app/models/inspection/form.rb
# frozen_string_literal: true

class Inspection::Form
  LIST = [
    '暫不選取',
    '天線維運記錄',
    'UPS維運紀錄',
    'MU設備維運紀錄',
    'RU設備維運紀錄',
    '終端假負載維運紀錄'
  ].freeze

  attr_reader :name

  def initialize(name)
    raise ArgumentError unless name.in? LIST

    @name = name
  end

  def self.all
    LIST.map { |name| new(name) }
  end

  def self.find_by(name:)
    new(name)
  end
end

app/models/inspection/history.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: inspection_histories
#
#  id                :bigint           not null, primary key
#  maintain_type     :string
#  results           :jsonb
#  serial_number     :integer
#  uploaded_at       :datetime
#  year              :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  equipment_item_id :bigint
#
# Indexes
#
#  index_inspection_histories_on_equipment_item_id  (equipment_item_id)
#
class Inspection::History < ApplicationRecord
  belongs_to :equipment_item, class_name: 'Equipment::Item'

  before_create :assign_serial_number

  form_accessors = []

  # 表單欄位的名稱
  # A_0_1_1 ~ A_200_10_5
  (1..5).each do |i|
    (1..10).each do |j|
      form_accessors.concat((0..200).map { |k| :"A_#{k}_#{j}_#{i}" })
    end
  end

  # 相片欄位名稱
  # P_0_1, P_0_2 ~ P_200_1, P_200_2
  (1..2).each do |i|
    form_accessors.concat((0..200).map { |j| :"P_#{j}_#{i}" })
  end

  base_accessors = [
    :updates,
    :draft,
    :started_at,
    :completed_at
  ]

  store :results, coder: JSON, accessors: base_accessors.concat(form_accessors)

  def record_update(reason)
    updates << { reason: reason, at: Time.zone.now }
  end

  def pdf_path_hirachy
    File.join(
      equipment_item.area.owner.name,
      equipment_item.area.name,
      equipment_item.component.code
    )
  end

  def form_number
    generate_form_number unless results[:form_number]

    results[:form_number]
  end

  def generate_form_number
    results[:form_number] = "#{Time.zone.now.strftime('%Y%m%d')}_#{equipment_item.display_name}"
  end

  def pdf_filename
    "#{form_number}.pdf"
  end

  def archive_link_path
    '/' + (
      [
        'archives',
        '巡檢歷史紀錄PDF',
        pdf_path_hirachy,
        pdf_filename
      ].join('/')
    )
  end

  def archive_file_path
    Rails.root.join(
      'public',
      'archives',
      '巡檢歷史紀錄PDF',
      pdf_path_hirachy,
      pdf_filename
    )
  end

  def start
    generate_form_number
    self.updates = []
    self.draft = true
    self.started_at = Time.zone.now
  end

  def started?
    !started_at.nil?
  end

  def complete
    self.draft = false
    self.completed_at = Time.zone.now
  end

  def completed?
    !completed_at.nil?
  end

  private

  def assign_serial_number
    number = self.class.where(
      year: year,
      equipment_item: equipment_item
    ).maximum(:serial_number)

    self.serial_number = number ? number + 1 : 1
  end
end

app/models/inspection/photo.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: inspection_photos
#
#  id         :bigint           not null, primary key
#  image_data :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  result_id  :integer
#
# Indexes
#
#  index_inspection_photos_on_result_id  (result_id)
#
class Inspection::Photo < ApplicationRecord
  include InspectionPhotoUploader::Attachment(:image)
end

app/models/inspection/result.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: inspection_results
#
#  id         :bigint           not null, primary key
#  result     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  history_id :integer
#  item_id    :integer
#
# Indexes
#
#  index_inspection_results_on_history_id  (history_id)
#  index_inspection_results_on_item_id     (item_id)
#
class Inspection::Result < ApplicationRecord
  belongs_to :history
  belongs_to :item

  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: :all_blank
end

app/controllers/inspection/histories_controller.rb
# frozen_string_literal: true

class Inspection::HistoriesController < ApplicationController
  ALL_ID = 9999

  before_action :set_inspection_history, only: %i[show pdf edit update destroy]

  # GET inspection/histories
  # GET inspection/histories.json
  def index
    cookies[:inspection_form_back_path] = request.path unless request.format.json?

    @layer1_areas = Area.select(:id, :name, :category_id).layer1

    if params[:layer1_area_id] && params[:layer2_area_id] && params[:equ_component_id]
      area = Area.find(params[:layer1_area_id])

      equ_items =
        if params[:layer2_area_id].to_i == ALL_ID
          area.sub_areas.map(&:equipment_items).flatten.uniq
        else
          Area.find(params[:layer2_area_id]).equipment_items.includes(:area, meta_datum: :component)
        end

      if params[:equ_component_id].to_i != ALL_ID
        equ_items = equ_items.filter do |item| 
          item.component.id == params[:equ_component_id].to_i
        end
      end

      inspection_histories = equ_items.map(&:inspection_histories).flatten.filter(&:started?)

      if params[:from] && params[:to]
        inspection_histories.filter! do |history|
          history.started_at.to_date.between?(params[:from].to_date, params[:to].to_date)
        end
      end


      respond_to do |format|
        format.json do
          render json: inspection_histories.map { |h|
            last_updated_at =
              if !h.updates.empty?
                h.updates.last[:at].to_datetime.strftime('%Y/%m/%d %H:%M:%S')
              elsif h.completed_at
                h.completed_at.to_datetime.strftime('%Y/%m/%d %H:%M:%S')
              else
                '未完成'
              end

            {
              id: h.id,
              layer1: area.name,
              layer2: h.equipment_item.area.name,
              component_name: h.equipment_item.component.name,
              has_fc_para: h.equipment_item.meta_datum.fc_para&.exists?,
              download_fc_para_url: download_pdf_equipment_meta_datum_path(h.equipment_item.meta_datum),
              year: h.year,
              serial_number: h.serial_number,
              form_number: h.form_number,
              started_at: h.started_at.to_datetime.strftime('%Y/%m/%d %H:%M:%S'),
              last_updated_at: last_updated_at
            }
          }
        end
      end
    end
  end

  # GET inspection/histories/1
  # GET inspection/histories/1.json
  def show
    @equipment_item = @inspection_history.equipment_item
    render "inspection/histories/forms/#{@inspection_history.equipment_item.inspection_form.name}.html.erb",
           layout: 'inspection_form'
  end

  def pdf
    @equipment_item = @inspection_history.equipment_item
    render "inspection/histories/forms/#{@inspection_history.equipment_item.inspection_form.name}.html.erb",
           layout: 'inspection_pdf'
  end

  # GET inspection/histories/new
  def new
    @equipment_item = Equipment::Item.find(params[:item_id])
    @inspection_history = @equipment_item.inspection_histories.build
    flash.now[:notice] = '若為新增巡檢表單請先點選右方『開始產製表單』'

    if @equipment_item.inspection_form?
      render "inspection/histories/forms/#{@equipment_item.inspection_form.name}.html.erb",
             layout: 'inspection_form'
    else
      render plain: '此設備尚未指定表單'
    end
  end

  # GET inspection/histories/1/edit
  def edit
    @inspection_history = Inspection::History.find(params[:id])
    @equipment_item = @inspection_history.equipment_item
    @mode = @inspection_history.completed_at ? 'update' : 'complete'

    render "inspection/histories/forms/#{@equipment_item.inspection_form.name}.html.erb",
           layout: 'inspection_form'
  end

  # POST inspection/histories
  # POST inspection/histories.json
  def create
    @inspection_history = Inspection::History.new(inspection_history_params)
    @inspection_history.start

    respond_to do |format|
      if @inspection_history.save
        format.html do
          redirect_to edit_inspection_history_url(@inspection_history),
                      notice: "開始巡檢，日期：#{@inspection_history.started_at.to_date}"
        end
        format.json { render :show, status: :created, location: @inspection_history }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT inspection/histories/1
  # PATCH/PUT inspection/histories/1.json
  def update
    @inspection_history.assign_attributes(inspection_history_params)

    upload_images

    if params[:complete]
      @inspection_history.complete
    elsif params[:update]
      @inspection_history.record_update(params[:reason])
    end

    respond_to do |format|
      if @inspection_history.save
        update_pdf_for(@inspection_history) unless params[:tmp]

        format.html do
          if params[:tmp]
            redirect_to edit_inspection_history_url(@inspection_history), notice: '已暫存'
          else
            redirect_to @inspection_history, notice: 'Inspection history was successfully updated.'
          end
        end

      else
        format.html { render :edit }
        format.json { render json: @inspection_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE inspection/histories/1
  # DELETE inspection/histories/1.json
  def destroy
    @inspection_history.destroy
    respond_to do |format|
      format.html do
        redirect_to inspection_histories_url, notice: 'Inspection history was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_inspection_history
    @inspection_history = Inspection::History.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def inspection_history_params
    params.require(:inspection_history).permit!
  end

  def upload_images
    (1..200).each do |m|
      (1..2).each do |n|
        column = "P_#{m}_#{n}"
        create_image_for(column) if inspection_history_params[column]
      end
    end
  end

  def update_pdf_for(inspection_history)
    pdf = WickedPdf.new.pdf_from_url(pdf_inspection_history_url(inspection_history), no_pdf_compression: false)

    relative_path = inspection_history.pdf_path_hirachy

    uploads_dir = Rails.root.join('public', 'uploads', '巡檢歷史紀錄PDF', relative_path)
    archives_dir = Rails.root.join('public', 'archives', '巡檢歷史紀錄PDF', relative_path)

    [uploads_dir, archives_dir].each do |dir|
      FileUtils.mkdir_p(dir) unless File.directory?(dir)

      path = Rails.root.join(
        dir,
        inspection_history.pdf_filename
      )

      File.open(path, 'wb') do |file|
        file << pdf
      end
    end
  end

  def create_image_for(column)
    return unless inspection_history_params[column]

    file_name = "#{column}.jpg"
    relative_path = File.join('uploads', '巡檢歷史紀錄照片', @inspection_history.id.to_s)

    dir = Rails.root.join('public', relative_path)
    FileUtils.mkdir_p(dir) unless File.directory?(dir)

    path = Rails.root.join(dir, file_name)

    File.open(path, 'wb') do |file|
      file.write(inspection_history_params[column].read)
    end

    @inspection_history.results[column] = File.join('/', relative_path, file_name)
  end
end

app/controllers/inspection/results_controller.rb
class Inspection::ResultsController < ApplicationController
  before_action :set_inspection_result, only: [:show, :edit, :update, :destroy]

  # GET /inspection/results
  # GET /inspection/results.json
  def index
    @inspection_results = Inspection::Result.all
  end

  # GET /inspection/results/1
  # GET /inspection/results/1.json
  def show
  end

  # GET /inspection/results/new
  def new
    @inspection_result = Inspection::Result.new
  end

  # GET /inspection/results/1/edit
  def edit
  end

  # POST /inspection/results
  # POST /inspection/results.json
  def create
    @inspection_result = Inspection::Result.new(inspection_result_params)

    respond_to do |format|
      if @inspection_result.save
        format.html { redirect_to @inspection_result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @inspection_result }
      else
        format.html { render :new }
        format.json { render json: @inspection_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inspection/results/1
  # PATCH/PUT /inspection/results/1.json
  def update
    respond_to do |format|
      if @inspection_result.update(inspection_result_params)
        format.html { redirect_to @inspection_result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @inspection_result }
      else
        format.html { render :edit }
        format.json { render json: @inspection_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspection/results/1
  # DELETE /inspection/results/1.json
  def destroy
    @inspection_result.destroy
    respond_to do |format|
      format.html { redirect_to inspection_results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inspection_result
      @inspection_result = Inspection::Result.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inspection_result_params
      params.require(:inspection_result).permit(:item_id, :result)
    end
end

app/helpers/inspection/results_helper.rb
module Inspection::ResultsHelper
end

app/views/inspection/histories/_images.html.erb
<tr >
  <td colspan="6">
    <%= title %><br>
    <% if inspection_history.results[column1.to_s] %>
      <%= image_tag inspection_history.results[column1.to_s], width: 450 %>
    <% end %>

    <% if inspection_history.results[column2.to_s] %>
      <%= image_tag inspection_history.results[column2.to_s], width: 450 %>
    <% end %>
  </td>
</tr>
<tr >
  <td colspan="6">
    <%= form.file_field column1  %>
    <%= form.file_field column2  %>
    <%= form.submit '暫存', name: 'tmp'  %>
  </td>
</tr>    

app/views/inspection/histories/_inspection_form_footer.html.erb
<tr>
  <td colspan="2">
    維運人員（簽）：</td>
  <td width="220" >　</td>
  <td colspan="2" >
    維運廠商（印）：</td>
  <td width="386" colspan="2" >　</td>
</tr>
<tr >
  <td colspan="7">
    ※繳交成果報告時，請維運人員簽名，並由維運廠商加蓋公司章(訂約章)或授權印章&nbsp;</td>
</tr>
</table>

<p><p>
  <% if @mode == 'update' %>
    編輯原因 <%= text_field_tag :reason %>
  <% end %>
  <%= form.submit '儲存上傳維運資料', name: @mode %>（請以鍵盤輸入）
  </p></p>

<script charset="utf-8">
  var reason_field = document.getElementById('reason')
  var update_btn = document.getElementsByName("update")[0]

  if (reason_field) {
    update_btn.disabled = true

    reason_field.onkeyup = function() {
      console.log(reason_field.value)
      if(reason_field.value.length > 0) {
        update_btn.disabled = false
      }

      if(reason_field.value.length === 0) {
        update_btn.disabled = true
      }
    }
  }
</script>

app/views/inspection/histories/edit.html.erb
<h1><%= @inspection_history.equipment_item.display_name %>巡檢</h1>

<%= render 'form', equipment_item: @inspection_history.equipment_item, inspection_history: @inspection_history %>

<%= link_to '內容', @inspection_history %> |
<%= link_to 'Back', equipment_item_path(@inspection_history.equipment_item) %>

app/views/inspection/histories/index.html.erb
<h1>歷史巡檢表單查詢</h1>

<div id="guide-app">
  
  <div id="divDropdown" class="dropdown">
    <div>
      工區：<select size="1" id="optArea1" v-model="layer1Selected">
        <option v-for="option in layer1Options" :value="option.id">
          {{ option.name }}
        </option>
      </select> &nbsp;&nbsp;
      篩選時間：    
      <%= select_date @from || 1.day.ago, { prefix: :from, end_year: Time.now.year } %> ~ 
      <%= select_date @to || Date.current, prefix: :to, end_year: Time.now.year %>
    </div>
    <p></p>
    <table style="display: inline; margin-right: 40px;">
      <tr id="tr2" style="background-color:#ffffff">
        <td>
          <input type="radio" value="equComponentFirst" v-model="filterType" onclick="document.getElementById('tr1').style.backgroundColor='#FFFFFF';document.getElementById('tr2').style.backgroundColor='#FFCC33';"> 
          &emsp;以設備類別查詢：
        </td>

        <td>
          &emsp;設備類別
          <select size="1" id="optEq" v-model="equComponentSelected.equComponentFirst" :disabled="!isEquComponentFirst">
            <option v-for="option in equComponentOptions.equComponentFirst" :value="option.id">
              {{ option.name }}
            </option>
          </select>

          &emsp;安裝位置
          <select size="1" id="optArea2" v-model="layer2Selected.equComponentFirst" :disabled="!isEquComponentFirst">
            <option v-for="option in layer2Options.equComponentFirst" :value="option.id">
              {{ option.name }}
            </option>
          </select>
        </td>
      </tr>
      <tr id="tr1" style="background-color:#ffffff">
        <td>
          <input type="radio" value="layer2First" v-model="filterType" onclick="document.getElementById('tr1').style.backgroundColor='#FFCC33';document.getElementById('tr2').style.backgroundColor='#FFFFFF';"> 
          &emsp;以安裝位置查詢：
        </td>

        <td>
          &emsp;安裝位置
          <select size="1" id="optArea2" v-model="layer2Selected.layer2First" :disabled="!isLayer2First">
            <option v-for="option in layer2Options.layer2First" :value="option.id">
              {{ option.name }}
            </option>
          </select>

          &emsp;設備類別
          <select size="1" id="optEq" v-model="equComponentSelected.layer2First" :disabled="!isLayer2First">
            <option v-for="option in equComponentOptions.layer2First" :value="option.id">
              {{ option.name }}
            </option>
          </select>
        </td>

      </tr>


    </table>

    <input @click="getHistories" :disabled="!isQueryable" type="button" value="查詢" id="btnSendResult" name="B1">
  </div>

  <p></p>

  <%= render partial: 'shared/jtable_print_and_csv_export_links' %>
  <table id="jTable" class="table">
    <thead class="thead-dark">
      <tr>
        <th>工區</th>
        <th>安裝於</th>
        <th>設備別</th>
        <th>年度</th>
        <th>次別</th>
        <th>表單號</th>
        <th>開始時間</th>
        <th>最後編輯時間</th>
        <th>功能</th>
      </tr>
    </thead>

    <tbody>
    <template v-if="targetItems.length > 0">
      <tr v-for="targetItem in targetItems">
        <td>{{ targetItem.layer1 }}</td>
        <td>{{ targetItem.layer2 }}</td>
        <td>{{ targetItem.component_name }}</td>
        <td>{{ targetItem.year }}</td>
        <td>{{ targetItem.serial_number }}</td>
        <td>{{ targetItem.form_number }}</td>
        <td>{{ targetItem.started_at }}</td>
        <td>{{ targetItem.last_updated_at }}</td>

        <td style="width: 15%">
          <a class="btn btn-primary" :href="showUrl(targetItem.id)">
            查看
          </a>
          <% unless current_user.viewer? %>
          <a class="btn btn-info" :href="editUrl(targetItem.id)">
            編輯
          </a>
          <% end %>
          <% if current_user.super_admin? || current_user.admin? %>
          <a class="btn btn-danger" href="#" @click="function(e) { e.preventDefault(); deleteHistory(targetItem.id) }">
            刪除
          </a>
          <% end %>
          <a class="btn btn-secondary" v-if="targetItem.has_fc_para" :href="targetItem.download_fc_para_url" target="_blank"> 
            手冊 
          </a>
        </td>
      </tr>
    </template>
    </tbody>
  </table>
</div>

<script>
var vueApp = true
</script>

<%= render partial: 'shared/jtable_and_csv_export_js' %>

<script>
new Vue({
  el: '#guide-app',
  data: {
    layer1Options: <%= raw json_escape(@layer1_areas.to_json) %>,
    layer2Options: { layer2First: [], equComponentFirst: [] },
    equComponentOptions: { layer2First: [], equComponentFirst: [] },
    layer1Selected: <%= @layer1_areas.first.id %>,
    layer2Selected: { layer2First: 0, equComponentFirst: 0 },
    equComponentSelected: { layer2First: 0, equComponentFirst: 0 },
    targetItems: [],
    filterType: null
  },

  computed: {
    isLayer2First: function() {
      return this.filterType === 'layer2First'
    },

    isEquComponentFirst: function() {
      return this.filterType === 'equComponentFirst'
    },

    isQueryable: function() {
      return this.isEquComponentFirst || this.isLayer2First
    }
  },

  mounted: function() {
    bindExportBtn()
    bindPrintBtn()
  },

  watch: {
    layer1Selected: function(newVal) {
      this.layer2Options = { layer2First: [], equComponentFirst: [] }
      this.equComponentOptions = { layer2First: [], equComponentFirst: [] }
      this.layer2Selected = { layer2First: 0, equComponentFirst: 0 },
      this.equComponentSelected = { layer2First: 0, equComponentFirst: 0 },
      this.filterType = null
      document.getElementById('tr1').style.backgroundColor='#FFFFFF'
      document.getElementById('tr2').style.backgroundColor='#FFFFFF'
    },

    filterType: function(newVal) {
      this.updateFirstLevelOptions(newVal, this.layer1Selected)
    },

    'layer2Selected.layer2First': function(newVal) {
      const self = this

      axios.get("<%= api_get_equ_component_path %>" + '?layer2_first=true&layer1_area_id=' + self.layer1Selected + '&layer2_area_id=' + newVal)
        .then(function(res) {
          self.equComponentOptions.layer2First = res.data
          self.equComponentSelected.layer2First = self.equComponentOptions.layer2First[0].id
        })
    },

    'equComponentSelected.equComponentFirst': function(newVal) {
      const self = this

      axios.get("<%= api_get_layer2_path %>" + '?equ_component_first=true&layer1_area_id=' + this.layer1Selected + '&equ_component_id=' + newVal)
      .then(function(res) {
        self.layer2Options.equComponentFirst = res.data
        self.layer2Selected.equComponentFirst = self.layer2Options.equComponentFirst[0].id
      })
    }
  },

  methods: {
    updateFirstLevelOptions: function(filterType, layer1) {
      const self = this

      if (filterType === 'layer2First') {
        axios.get("<%= api_get_layer2_path %>" + '?layer2_first=true&layer1_area_id=' + layer1)
          .then(function(res) {
            self.layer2Options.layer2First = res.data
            self.layer2Selected.layer2First = self.layer2Options.layer2First[0].id
          })
      }

      if (filterType === 'equComponentFirst') {
        axios.get("<%= api_get_equ_component_path %>" + '?equ_component_first=true&layer1_area_id=' + layer1)
          .then(function(res) {
            self.equComponentOptions.equComponentFirst = res.data
            self.equComponentSelected.equComponentFirst = self.equComponentOptions.equComponentFirst[0].id
          })
      }
    },

    getFromDate: function() {
      const year = $('#from_year').val()
      const month = $('#from_month').val()
      const day = $('#from_day').val()

      return year + '-' + month + '-' + day
    },

    getToDate: function() {
      const year = $('#to_year').val()
      const month = $('#to_month').val()
      const day = $('#to_day').val()

      return year + '-' + month + '-' + day
    },

    getHistories: function() {
      if (jTable) {
        jTable.destroy()
      }

      const self = this
      const layer2Id = this.layer2Selected[this.filterType]
      const equComponentId = this.equComponentSelected[this.filterType]
      const from = this.getFromDate()
      const to = this.getToDate()

      axios.get("<%= inspection_histories_path(format: :json) %>" + '?layer1_area_id=' + this.layer1Selected + '&layer2_area_id=' + layer2Id + '&equ_component_id=' + equComponentId + '&from=' + from + '&to=' + to)
        .then(function(res) { self.targetItems = res.data })
        .then(function() { self.$nextTick(initDataTable()) })
    },

    deleteHistory: function(id) {
      const self = this
      const csrfToken = document.querySelector("meta[name=csrf-token]").content

      if (confirm('Are you sure?')) {
        axios.delete(self.deleteUrl(id), {
          headers: {
            'X-CSRF-Token': csrfToken
          }
        })
        .then(function() {
          self.getHistories()
        })
      }
    },

    editUrl: function(id) {
      return '/inspection/histories/' + id + '/edit'
    },

    showUrl: function(id) {
      return '/inspection/histories/' + id
    },

    deleteUrl: function(id) {
      return '/inspection/histories/' + id + '.json'
    },
  }
})
</script>

app/views/inspection/histories/new.html.erb
<h1><%= @equipment_item.display_name %>巡檢</h1>

<%= render 'form', equipment_item: @equipment_item, inspection_history: @inspection_history %>

<%= link_to 'Back', equipment_item_path(@equipment_item) %>

app/views/inspection/histories/show.html.erb
<div>
  <ol>
    <li>設備名稱：<%= @inspection_history.equipment_item.display_name %></li>
    <li><%= @inspection_history.year %> 年第 <%= @inspection_history.serial_number %> 次巡檢</li>
    <li>上傳時間：<%= @inspection_history.uploaded_at %></li>
  </ol>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>編號</th>
      <th>巡檢項目</th>
      <th>巡檢結果</th>
      <th>照片</th>
    </tr>
  </thead>

  <tbody>
    <% @inspection_history.results.each_with_index do |result, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= result.item.content %></td>
        <td>
          <%= result.result %>
        </td>
        <td>
          <% result.photos.each do |photo| %>
            <%= image_tag photo.image_url, style: 'width: 200px' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '編輯', edit_inspection_history_path(@inspection_history) %> |
<%= link_to 'Back', equipment_item_path(@inspection_history.equipment_item) %>